name: Build Windows Build Agent
on:
  push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          push: true
          context: ./windows/
          repository: NETWORG/azdo-docker-agents/windows
          tags: latest