name: Build Windows Agent
on:
  push
jobs:
  push_to_registry:
    name: Build and push to Container Registry
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to Container Registry
        working-directory: ./windows/
        run: |
          docker login ghcr.io -u $env:USER -p $env:TOKEN
          docker build -t ghcr.io/NETWORG/azdo-docker-agents/windows:latest
          docker image push ghcr.io/NETWORG/azdo-docker-agents/windows:latest
          docker logout
        env:
          USER: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}